"""add content column to embeddings

Revision ID: 8de6daf17a16
Revises: 56d3c2f77a5e
Create Date: 2026-08-03 19:11:28.033502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8de6daf17a16'
down_revision: Union[str, None] = '56d3c2f77a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'content')
    # ### end Alembic commands ###
