"""add tags columns to resume_versions and job_postings

Revision ID: a60c15bdb213
Revises: 8de6daf17a16
Create Date: 2026-08-11 16:37:04.030588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a60c15bdb213'
down_revision: Union[str, None] = '8de6daf17a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default='[]' is required, not cosmetic: without it this NOT NULL
    # column addition fails outright against a table that already has rows
    # (existing rows have nothing to satisfy the constraint with otherwise).
    op.add_column(
        'job_postings',
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    op.add_column(
        'resume_versions',
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'tags')
    op.drop_column('job_postings', 'tags')
    # ### end Alembic commands ###
